[package]
name = "submission-archiver"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.9.8"

reqwest = { version = "0.12.25", features = ["blocking", "json"] }
scraper = "0.25"
